function org_kie_workbench_drools_KIEDroolsWebapp(){var Q='bootstrap',R='begin',S='gwt.codesvr.org.kie.workbench.drools.KIEDroolsWebapp=',T='gwt.codesvr=',U='org.kie.workbench.drools.KIEDroolsWebapp',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='org_kie_workbench_drools_KIEDroolsWebapp',qb='Failed to load ',rb='head',sb='meta',tb='name',ub='org.kie.workbench.drools.KIEDroolsWebapp::',vb='::',wb='gwt:property',xb='content',yb='=',zb='gwt:onPropertyErrorFn',Ab='Bad handler "',Bb='" for "gwt:onPropertyErrorFn"',Cb='gwt:onLoadErrorFn',Db='" for "gwt:onLoadErrorFn"',Eb='#',Fb='?',Gb='/',Hb='img',Ib='clear.cache.gif',Jb='baseUrl',Kb='org.kie.workbench.drools.KIEDroolsWebapp.nocache.js',Lb='base',Mb='//',Nb='locale',Ob='default',Pb='locale=',Qb=7,Rb='&',Sb='__gwt_Locale',Tb='_',Ub='Unexpected exception in locale detection, using default: ',Vb=2,Wb=3,Xb=4,Yb=5,Zb=6,$b='user.agent',_b='webkit',ac='safari',bc='msie',cc=10,dc=11,ec='ie10',fc=9,gc='ie9',hc=8,ic='ie8',jc='gecko',kc='gecko1_8',lc='selectingPermutation',mc='org.kie.workbench.drools.KIEDroolsWebapp.devmode.js',nc='fr',oc='0E17F18E8FC1B41F9C30DFFC05C3C2E6',pc='ja',qc='1EEC5431CE84B46881A6B22F918A9517',rc='es',sc='1F1E44F219622C4BC8A5DF60F8CA369D',tc='443FAE7CA24FAD71A0687165A8EF1361',uc='5FB49A4F24E32923FF7C5C24BEDE41B6',vc='zh_CN',wc='865A4713CBB7F1291BDBA0AA12BBEE72',xc='9DEFE3F072847334D562401D28FDB4CE',yc='A24C911553E7BDD3C5AA290CBE16D885',zc='de',Ac='B5162C3F1EDB5E26DD4422C3475914D7',Bc='BA11BFAF5446BE7E273C09EB5A5AD622',Cc='pt_BR',Dc='CE951D2BE32E6AE615853FEFD4575C26',Ec='DC8A0DCB68A6CE99334A83CBCA49F098',Fc='DD700D2B65E891DAFE33A8C5B80A7A05',Gc='F457C87680EB6AD4936535D4191A4263',Hc=':',Ic='.cache.js',Jc='link',Kc='rel',Lc='stylesheet',Mc='href',Nc='loadExternalRefs',Oc='patternfly/dist/css/patternfly.min.css',Pc='patternfly/dist/css/patternfly-additions.min.css',Qc='uberfire-patternfly.css',Rc='css/bootstrap-datepicker3-1.4.0.min.cache.css',Sc='css/bootstrap-select-1.6.4.min.cache.css',Tc='css/bootstrap-select-fix-1.6.4.min.cache.css',Uc='css/bootstrap-switch-3.3.2.min.cache.css',Vc='css/bootstrap-datetimepicker-2.3.1.min.cache.css',Wc='css/home.css',Xc='css/typeahead-0.10.5.min.cache.css',Yc='css/positioned-tabs-1.0.0.min.cache.css',Zc='css/bootstrap-slider-4.5.6.min.cache.css',$c='css/kie-drools-wb.css',_c='end',ad='http:',bd='file:',cd='_gwt_dummy_',dd='__gwtDevModeHook:org.kie.workbench.drools.KIEDroolsWebapp',ed='Ignoring non-whitelisted Dev Mode URL: ',fd=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
org_kie_workbench_drools_KIEDroolsWebapp.__sendStats=t;org_kie_workbench_drools_KIEDroolsWebapp.__moduleName=U;org_kie_workbench_drools_KIEDroolsWebapp.__errFn=null;org_kie_workbench_drools_KIEDroolsWebapp.__moduleBase=W;org_kie_workbench_drools_KIEDroolsWebapp.__softPermutationId=X;org_kie_workbench_drools_KIEDroolsWebapp.__computePropValue=null;org_kie_workbench_drools_KIEDroolsWebapp.__getPropMap=null;org_kie_workbench_drools_KIEDroolsWebapp.__installRunAsyncCode=function(){};org_kie_workbench_drools_KIEDroolsWebapp.__gwtStartLoadingFragment=function(){return null};org_kie_workbench_drools_KIEDroolsWebapp.__gwt_isKnownPropertyValue=function(){return false};org_kie_workbench_drools_KIEDroolsWebapp.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};org_kie_workbench_drools_KIEDroolsWebapp.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[org_kie_workbench_drools_KIEDroolsWebapp.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
org_kie_workbench_drools_KIEDroolsWebapp.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(org_kie_workbench_drools_KIEDroolsWebapp.__errFn){n.onerror=function(){org_kie_workbench_drools_KIEDroolsWebapp.__errFn(pb,new Error(qb+code))}}r.getElementsByTagName(rb)[X].appendChild(n)}
org_kie_workbench_drools_KIEDroolsWebapp.__startLoadingFragment=function(a){return G(a)};org_kie_workbench_drools_KIEDroolsWebapp.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(sb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,db);if(j.indexOf(vb)>=X){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;org_kie_workbench_drools_KIEDroolsWebapp.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Jb);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Lb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return org_kie_workbench_drools_KIEDroolsWebapp.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=X){var f=d.substring(e+Qb);var g=d.indexOf(Rb,e);if(g<X){g=d.length}b=d.substring(e+Qb,g)}}if(!b){b=__gwt_getMetaProperty(Nb)}if(!b){b=q[Sb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Nb,b)){var h=b.lastIndexOf(Tb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Ub+a)}q[Sb]=c;return b||Ob};l[Nb]={de:X,'default':Y,es:Vb,fr:Wb,ja:Xb,pt_BR:Yb,zh_CN:Zb};m[$b]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(_b)!=-1}())return ac;if(function(){return a.indexOf(bc)!=-1&&(b>=cc&&b<dc)}())return ec;if(function(){return a.indexOf(bc)!=-1&&(b>=fc&&b<dc)}())return gc;if(function(){return a.indexOf(bc)!=-1&&(b>=hc&&b<dc)}())return ic;if(function(){return a.indexOf(jc)!=-1||b>=dc}())return kc;return db};l[$b]={gecko1_8:X,ie10:Y,ie8:Vb,ie9:Wb,safari:Xb};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};org_kie_workbench_drools_KIEDroolsWebapp.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};org_kie_workbench_drools_KIEDroolsWebapp.__computePropValue=n;q.__gwt_activeModules[U].bindings=org_kie_workbench_drools_KIEDroolsWebapp.__getPropMap;t(Q,lc);if(s()){return G(mc)}var o;try{k([nc,kc],oc);k([pc,kc],qc);k([rc,kc],sc);k([Ob,ac],tc);k([Ob,kc],uc);k([vc,ac],wc);k([pc,ac],xc);k([rc,ac],yc);k([zc,ac],Ac);k([vc,kc],Bc);k([Cc,kc],Dc);k([zc,kc],Ec);k([Cc,ac],Fc);k([nc,ac],Gc);o=i[n(Nb)][n($b)];var p=o.indexOf(Hc);if(p!=-1){j=parseInt(o.substring(p+Y),cc);o=o.substring(X,p)}}catch(a){}org_kie_workbench_drools_KIEDroolsWebapp.__softPermutationId=j;return G(o+Ic)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(Jc);b.setAttribute(Kc,Lc);b.setAttribute(Mc,G(a));r.getElementsByTagName(rb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Nc,R);c(Oc);c(Pc);c(Qc);c(Rc);c(Sc);c(Tc);c(Uc);c(Vc);c(Wc);c(Xc);c(Yc);c(Zc);c($c);t(Nc,_c)}
D();org_kie_workbench_drools_KIEDroolsWebapp.__moduleBase=F();v[U].moduleBase=org_kie_workbench_drools_KIEDroolsWebapp.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==ad||q.location.protocol==bd);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=cd;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=dd;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(ed+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+fd]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(rb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,_c);C(J);return true}
org_kie_workbench_drools_KIEDroolsWebapp.succeeded=org_kie_workbench_drools_KIEDroolsWebapp();